### ISSUE TITLE
Add a dropdown to quickly switch between graphql schema endpoints

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-graphql-devtools#11]
#9 added support for multi-schema. You can manually specify which schema the graphql dev tools should be querying with a URL parameter.

Adding a dropdown ... or some other mechanism ... to quickly switch between schema would make the dev tool more developer friendly.

# Related PR
* [ ] #12

**Comment by robbieaverill** [comment]
100%! I just had the same thought =D
