### ISSUE TITLE
Prod usage?

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql-devtools#31]
Currently we recommend `composer require --dev`, which would filter this out of (well managed) prod deployments. There are no extra checks in the config or controller layer around "dev only" right now. But in practice, the route doesn't work because it's detected as a "confirmed action" under the `dev/*` path, and goes into infinite loops.

Option A: Allow opt-in to prod usage through `composer require` without `--dev`, caution that it's up to the dev to secure that route (e.g. IP allowlisting in their CDN). 

Option B: Allow opt-in to prod usage, but also redirect to `Security/login`

Option C: Deny prod usage by not registering the route in prod, but allow intrepid devs to register their own routes

**Comment by unclecheese** [comment]
It's already behind the DevelopmentAdmin controller, so I think whatever security measures we apply on prod would be above and beyond what we're doing for database builds, right?

**Comment by chillu** [comment]
True that, and I just tested that it indeed works in `live` mode, after you login. I think the infinite loop was due to the misconfigured controller in the GraphQL 4.x compat PR.
