### ISSUE TITLE
Schema initialise task

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-graphql-devtools#45]
There's too much boilerplate in setting up a default schema. Create a task to automate some of that process.

## Acceptance criteria
- [ ] There's a tasks to make it easy to quickly initialise a GraphQL  schema on the graphql dev tools module.
- [ ] This wonderful feature is highlighted in the doc.

## PRs
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/53
- https://github.com/silverstripe/developer-docs/pull/493
- https://github.com/silverstripe/silverstripe-graphql/pull/433
- https://github.com/silverstripe/silverstripe-framework/pull/10218 (needs to be redone for developer-docs)

**Comment by sabina-talipova** [comment]
PRs have been merged. Task is completed.
