### ISSUE TITLE
CMS5 compatibility for GraphQL dev tools

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-graphql-devtools#47]
## Acceptance criteria
- New branch is created to track GraphQL v5
- Dependencies are upgraded
- All GraphQL v3 logic is removed
- Beta for CMS5 is tagged

## Notes
- There isn't test on this. So we will need to smoke test it to make sure it works.
- There is a JS bundle in there, but it shouldn't interact with our webpack config begause it doesn't add anything to the CMS.

## PRs
- https://github.com/silverstripe/recipe-kitchen-sink/pull/38

**Comment by emteknetnz** [comment]
We don't need to create a new branch for this, I've validated that the `1` branch that currently has a `"silverstrpe/graphql": "^3 || ^4 || ^5"` dependency works with silverstripe 5

You can get this running quickly by just using the admin schema as the default schema for devtools:

```
SilverStripe\GraphQLDevTools\Controller:
  # show two schemas
  schemas:
    # - default
    - admin
  # default schema that is selected
  default_schema: admin 
```

## Testing steps
- Composer require silverstripe/graphql-dev-tool: 1.x-dev
- Add in the yml above
- dev/build flush=1
- Ensure you are logged in to admin
- Navigate to /dev/graphql/ide
- Click the "Schema" tab on the right - it shows the schema

**Comment by emteknetnz** [comment]
We should
a) release 1.0.0-beta1 (there's currently no releases)
b) Add silverstripe/graphql-devtools to the root of recipe-kitchen-sink so that it gets released

**Comment by emteknetnz** [comment]
Have tagged 1.0.0
