### ISSUE TITLE
/dev/graphiql doesn't require log-in

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-graphql-devtools#6]
Generally speaking, anything other the /dev URL should require an admin login. This does not.

Now, this doesn't really introduce additional attack surface beyond what would already be exposed by the GraphQL API itself, but it seems untidy to leave this open.

**Comment by Firesphere** [comment]
In addition, if you're _not_ logged in, the documentation explorer doesn't work.

**Comment by chillu** [comment]
Addressed with https://github.com/silverstripe/silverstripe-graphql-devtools/pull/14
